# Generated by Django 3.2.6 on 2021-08-18 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('meat dish', 'Meat dish'), ('vegetarian dish', 'Vegetarian dish'), ('vegan dish', 'Vegan dish')], max_length=15)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('ingredients', models.TextField(blank=True, max_length=500)),
                ('instructions', models.TextField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='recipes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
